spring.application.name=inventory



#server.port=8080
server.servlet.context-path=/api

#spring.datasource.url=jdbc:postgresql://localhost:5432/alzaidan_db
#spring.datasource.username=postgres
#spring.datasource.password=amina
#
#spring.jpa.hibernate.ddl-auto=update


server.port=${PORT:8080}

# ========================
# Database
# ========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.open-in-view=false

#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}

#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=AlZaidanGlobalInvestmentSecretKeyForJWTTokenSigning2025
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

logging.level.com.alzaidan=INFO


spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


