spring.application.name=inventory



#server.port=8080
server.servlet.context-path=/api

#spring.datasource.url=jdbc:postgresql://localhost:5432/alzaidan_db
#spring.datasource.username=postgres
#spring.datasource.password=amina
#
#spring.jpa.hibernate.ddl-auto=update


server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=AlZaidanGlobalInvestmentSecretKeyForJWTTokenSigning2025
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

logging.level.com.alzaidan=INFO


spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


